remote_theme: b2a3e8/jekyll-theme-console
style: hacker
footer: 'Check out the place where this is hosted at <a href="https://github.com/Neko920/Neko920.github.io">GitHub</a>'
header_pages:
  - &#124;Whiplash.md
  - &#124;Philosophy.md
